{% set name = "ezdag" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezdag-{{ version }}.tar.gz
  sha256: 71ff7e0c377df330ded17cc2c9cdf529adc8691822a66d9a466a3ba1d301809d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - python-htcondor >=9

test:
  imports:
    - ezdag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/patrick.godwin/ezdag
  doc_url: https://docs.ligo.org/patrick.godwin/ezdag/
  summary: high-level HTCondor DAG generation library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - myNameIsPatrick
