{% set name = "ezdag" %}
{% set version = "0.4.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ezdag-{{ version }}.tar.gz
  sha256: 569a6981557950a76fb54e58d41d759b5ac13ac202bfbd5a5a318cd7b497fc6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - python-htcondor >=9

test:
  requires:
    - python {{ python_min }}
    - pip
    - graphviz
    - python-graphviz
    - pytest
    - pytest-cov
    - pytest-datadir
  commands:
    - pip check
    - pip show ezdag
    - pytest -ra --pyargs ezdag

about:
  home: https://git.ligo.org/patrick.godwin/ezdag
  doc_url: https://docs.ligo.org/patrick.godwin/ezdag/
  summary: high-level HTCondor DAG generation library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - myNameIsPatrick
